name: Build Release

on:
    workflow_dispatch:

jobs:
    release:
        permissions:
            contents: write
            pull-requests: read
        uses: Yueby/shared-workflows/.github/workflows/unity-package-release.yml@main
        with:
            package-name: ${{ vars.PACKAGE_NAME }}

    notify-listing:
        needs: release
        runs-on: ubuntu-latest
        steps:
            - name: Trigger Workflows
              uses: actions/github-script@v7
              with:
                github-token: ${{ fromJson(secrets.PAT).token }}
                script: |
                  const config = JSON.parse('${{ secrets.PAT }}');
                  console.log('Config loaded:', JSON.stringify(config, null, 2));
                  
                  for (const target of config.targets) {
                    console.log(`Triggering ${target.workflow} in repository: ${target.repo}`);
                    try {
                      await github.rest.actions.createWorkflowDispatch({
                        owner: context.repo.owner,
                        repo: target.repo,
                        workflow_id: target.workflow,
                        ref: 'main'
                      });
                      console.log('Successfully triggered workflow');
                    } catch (error) {
                      console.error('Error triggering workflow:', error);
                      throw error;
                    }
                  }
